# Generated by Django 3.1 on 2020-08-13 07:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/images/ninja.png', upload_to=account.models.img_upload_directory),
        ),
    ]
