# Generated by Django 3.1 on 2020-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200813_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='08-08-2020'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='Seoul, South Korea', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='9526622226', max_length=11),
        ),
    ]
