# Generated by Django 3.1 on 2020-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Enter Your bio'),
        ),
        migrations.AddField(
            model_name='website',
            name='cv_link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
